version: "3.7"

services:
  backend:
    image: ${DOCKER_REGISTRY:-bkw}bkwbackendapi:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: Backend/BKW.Backend.Api/Dockerfile
    ports:
      - 42069:80
    depends_on:
      - db
    networks:
      - bkw-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "BkwPassword42!"
      ACCEPT_EULA: "Y"
    networks:
      - bkw-network
    #volumes:
     # - bkw-data:/var/opt/mssql

  parser:
    image: ${DOCKER_REGISTRY:-bkw}parser:${IMAGE_TAG:-latest}
    build:
      context: ../Parser/BKW.Parser/App/
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    networks:
      - bkw-network            

#volumes:
  #bkw-data:
    # external: false

networks:
  bkw-network:
    driver: bridge
