version: "3.7"

services:
  backend:
    image: ${DOCKER_REGISTRY:-bkw}bkwbackendapi:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: Backend/BKW.Backend.Api/Dockerfile
    ports:
      - 42069:80
    depends_on:
      - db
    networks:
      - bkw-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "BkwPassword42!"
      ACCEPT_EULA: "Y"
    networks:
      - bkw-network

  frontend:
    build:
      context: ../Web/BKW.Web/App
      dockerfile: Dockerfile
    volumes:
      - ../Web/BKW.Web/App/src:/code/src
      - ../Web/BKW.Web/App/public:/code/public
    ports:
      - 3000:3000
    networks:
      - bkw-network
    depends_on:
      - backend

  parser:
    image: ${DOCKER_REGISTRY:-bkw}parser:${IMAGE_TAG:-latest}
    build:
      context: ../Parser/BKW.Parser/App/
      dockerfile: Dockerfile
    networks:
      - bkw-network     

networks:
  bkw-network:
    driver: bridge
